export const typeGradient: { [key: string]: string } = {
  normal: "bg-gradient-to-t from-gray-400 to-transparent",
  fire: "bg-gradient-to-t from-red-500 to-transparent",
  water: "bg-gradient-to-t from-blue-500 to-transparent",
  electric: "bg-gradient-to-t from-yellow-400 to-transparent",
  grass: "bg-gradient-to-t from-green-500 to-transparent",
  ice: "bg-gradient-to-t from-blue-300 to-transparent",
  fighting: "bg-gradient-to-t from-red-600 to-transparent",
  poison: "bg-gradient-to-t from-purple-500 to-transparent",
  ground: "bg-gradient-to-t from-yellow-600 to-transparent",
  flying: "bg-gradient-to-t from-indigo-400 to-transparent",
  psychic: "bg-gradient-to-t from-pink-500 to-transparent",
  bug: "bg-gradient-to-t from-green-400 to-transparent",
  rock: "bg-gradient-to-t from-yellow-700 to-transparent",
  ghost: "bg-gradient-to-t from-purple-600 to-transparent",
  dragon: "bg-gradient-to-t from-indigo-600 to-transparent",
  dark: "bg-gradient-to-t from-gray-700 to-transparent",
  steel: "bg-gradient-to-t from-gray-400 to-transparent",
  fairy: "bg-gradient-to-t from-pink-300 to-transparent",
};
