export const typeIcons: { [key: string]: string } = {
  normal: "normal.svg",
  fire: "fire.svg",
  water: "water.svg",
  electric: "electric.svg",
  grass: "grass.svg",
  ice: "ice.svg",
  fighting: "sword.svg",
  poison: "poison.svg",
  ground: "ground.svg",
  flying: "flying.svg",
  psychic: "psychic.svg",
  bug: "bug.svg",
  rock: "rock.svg",
  ghost: "ghost.svg",
  dragon: "dragon.svg",
  dark: "moonhalf.svg",
  steel: "steel.svg",
  fairy: "fairy.svg",
};
